/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.ventas;

import controllers.AccountJpaController;
import controllers.BillingJpaController;
import controllers.ConfigurationsJpaController;
import controllers.PaymentJpaController;
import controllers.exceptions.NonexistentEntityException;
import entities.Account;
import entities.Billing;
import entities.Configurations;
import entities.Payment;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import utilitarios.Utilitario;
import ventanas.reportes.reporteMasVendido;

/**
 *
 * @author macbookpro
 */
public class CobroFacturaForm extends javax.swing.JDialog {

    private Billing billing;
    private Account account;
    private BigDecimal quote;
    private PaymentJpaController paymentController;
    private AccountJpaController accountController;
    private BillingJpaController billingController;
    private ConfigurationsJpaController configController;
    public Configurations config;

    /**
     * Creates new form CobroForm
     *
     * @param parent
     * @param modal
     */

    public CobroFacturaForm(java.awt.Frame parent, boolean modal, Billing billing) {
        super(parent, modal);
        initComponents();
        this.billing = billing;
        this.account = billing.getAccountCollection().get(0);
        this.quote = billing.getTotal();
        fijarDatos();
        System.out.println("bal cons: " + this.account.getBalance());
        paymentController = new PaymentJpaController();
        accountController = new AccountJpaController();
        billingController = new BillingJpaController();
        configController = new ConfigurationsJpaController();
        this.btnRegistrarPago.setEnabled(false);

        Map<String, Object> variables = new HashMap<>();
        variables.put("code", "institutionName");
        config = configController.namedQuery("Configurations.findByCode", variables).get(0);
        
    }

    /**
     *
     */
    private void fijarDatos() {
        this.lblSaldo.setText(this.quote.toString());
        this.txtPago.setText("00.00");
        this.txtCambio.setText("00.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        txtPago = new javax.swing.JTextField();
        btnRegistrarPago = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();

        jButton2.setText("Registrar pago");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de pagos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Registro de pago");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Pago: ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("Cambio:");

        txtCambio.setEditable(false);
        txtCambio.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtCambio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCambio.setText("5,00");

        txtPago.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPago.setText("70,00");
        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });
        txtPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPagoFocusGained(evt);
            }
        });
        txtPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPagoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagoKeyReleased(evt);
            }
        });

        btnRegistrarPago.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnRegistrarPago.setText("Registrar pago");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Total Factura");

        lblSaldo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setText("65,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnRegistrarPago)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoKeyPressed

    }//GEN-LAST:event_txtPagoKeyPressed

    /**
     * Accion del boton registrar pago, anade una cuota de pago, o en su defecto
     * si no hay mas cuotas por pagar se cancela la cuenta por cobrar y se
     * imprime un comprobante de pago
     *
     * @param evt
     */
    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        try {
            //solo grabar los valores
            //grabar el abono
            Payment payment = new Payment();
            payment.setAccountId(this.account);
            payment.setValue(this.quote);
            payment.setBalance(account.getBalance());
            payment.setDatePayment(new Date());
            paymentController.create(payment);

            BigDecimal newBalance = this.account.getBalance().subtract(this.quote);
            if (newBalance.compareTo(BigDecimal.ZERO) == 0) {
                account.setState("Pagada");
            }
            account.setBalance(newBalance);
            accountController.edit(this.account);
            billing.setState("Pagada");
            billingController.edit(billing);
//            ctasCobrar.registerPayment();

            //imprimir el comprobante
            String reportPath = Utilitario.getValue("pathJasper") + "comPago.jasper";

            try {
                Map parametersMap = new HashMap();
                parametersMap.put("institution", config.getValue());
                List<Billing> billings = new ArrayList<Billing>();
                billings.add(billing);
                FileInputStream fis = new FileInputStream(reportPath);
                BufferedInputStream bufferedInputStream = new BufferedInputStream(fis);
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(bufferedInputStream);
                JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(billings);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, beanCollectionDataSource);
                // view report to UI
                // JasperViewer.viewReport(jasperPrint, false);
                JasperPrintManager.printReport(jasperPrint, false);
            } catch (JRException | FileNotFoundException ex) {
                Logger.getLogger(reporteMasVendido.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(CobroFacturaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    /**
     * Accion al momento de digitar una cantidad, verificia si es mayor al total
     * a pagar caso contrario desactiva el boton
     *
     * @param evt
     */
    private void txtPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoKeyReleased
        String value = txtPago.getText();
        if (value.isEmpty()) {
            this.btnRegistrarPago.setEnabled(false);
            return;
        }
        try {
            Double converted = Double.parseDouble(value);
            if (converted <= 0) {
                this.btnRegistrarPago.setEnabled(false);
                return;
            }
            BigDecimal change = new BigDecimal(converted).subtract(this.quote);
            change = change.setScale(2, BigDecimal.ROUND_HALF_UP);
            this.txtCambio.setText(change.toString());
            if (change.compareTo(BigDecimal.ZERO) < 0) {
                this.btnRegistrarPago.setEnabled(false);
            } else {
                this.btnRegistrarPago.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println("=>" + e);
            JOptionPane.showMessageDialog(this, "Ingrese valores correctos", "Error", JOptionPane.ERROR_MESSAGE);
            this.btnRegistrarPago.setEnabled(false);
        }
    }//GEN-LAST:event_txtPagoKeyReleased

    /**
     * Cierra el dialogo de cobro
     *
     * @param evt
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        try {
            //ANULAR LA FACTURA
            billing.setState("ANULADA");
            billingController.edit(billing);
            System.out.println("=====>aquiiiiiiiiiiiii" + billing.getId());
            this.dispose();
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(CobroFacturaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CobroFacturaForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        btnRegistrarPagoActionPerformed(evt);
    }//GEN-LAST:event_txtPagoActionPerformed

    private void txtPagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPagoFocusGained
        txtPago.selectAll();
    }//GEN-LAST:event_txtPagoFocusGained

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public BigDecimal getQuote() {
        return quote;
    }

    public void setQuote(BigDecimal quote) {
        this.quote = quote;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
