/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.administracion;

import controllers.UsersJpaController;
import entities.ClientProvider;
import entities.Users;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import utilitarios.Utilitario;

/**
 *
 * @author macbookpro
 */
public class UsuarioForm extends javax.swing.JDialog {

    public String sexo = "";
    public int familia = 0;
    public int producto = 0;
    public int factura = 0;
    public int ctaCobrar = 0;
    public int repVenta = 0;
    public int repCta = 0;
    public int repMas = 0;
    public int usuarioopt = 0;
    public int config = 0;
    public int clientes = 0;
    public static Map<String, Integer> llaves;
    private UsersJpaController controller;
    /**
     * Creates new form ClienteForm
     */
    public UsuarioForm(java.awt.Frame parent, boolean modal, Users user) {
        super(parent, modal);
        initComponents();
        this.user = user;
        sexo = "M";
        fijarEntidad();
        llaves = new HashMap<>();
        controller = new  UsersJpaController();
    }

    private void fijarEntidad() {
        nombres.setText(this.user.getPersonId().getNames());
        apellidos.setText(this.user.getPersonId().getLastname());
        identificacion.setText(this.user.getPersonId().getPassport());
        direccion.setText(this.user.getPersonId().getAddress());
        correo.setText(this.user.getPersonId().getEmail());
        usuario.setText(this.user.getNick());
        rol.setSelectedItem(this.user.getRol());
        if (this.user.getId() == null) {
            clave.setEnabled(true);
            cambiarClave.setVisible(false);
        } else {
            clave.setEnabled(false);
            cambiarClave.setVisible(true);
            //fijar los permisos de usuario
            String permisos = this.user.getPermissions(); 
            if (permisos != null && !permisos.isEmpty()) {
                createHashMap(permisos);
                familiaCh.setSelected(buscar("familia"));
                prodCH.setSelected(buscar("producto"));
                CtasCH.setSelected(buscar("ctas"));
                facturasCH.setSelected(buscar("factura"));
                clientesCH.setSelected(buscar("clientes"));
                ReporteVentasCH.setSelected(buscar("reporteVentas"));
                ReporteCtasCH.setSelected(buscar("reporteCta"));
                ReporteMsVendidoCH.setSelected(buscar("reporteMas"));
                UsuariosCH.setSelected(buscar("usuarios"));
                ConfigCH.setSelected(buscar("configuracion"));

            }
        }

        if (this.user.getPersonId().getSex().equals("M")) {
            sexo = "M";
            masculino.setSelected(true);
        } else {
            sexo = "F";
            femenino.setSelected(true);
        }

        if (this.user.getActive()) {
            estado.setSelected(true);
        }
    }

    /**
     * 
     * @param permisos 
     */
    public static void createHashMap(String permisos) {
        llaves = new HashMap<>();
        String[] perms = permisos.split(",");
        for (String perm : perms) {
            String values[] = perm.split("=", 2); // max 2 parts  
            llaves.put(values[0], Integer.valueOf(values[1]));
        }
    }

    public static boolean buscar(String key) {
        System.out.println("=====>" + key);
        if (llaves.containsKey(key)) {
            return (llaves.get(key) == 1) ? true : false;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        rol = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        clave = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        estado = new javax.swing.JCheckBox();
        cambiarClave = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        familiaCh = new javax.swing.JCheckBox();
        prodCH = new javax.swing.JCheckBox();
        clientesCH = new javax.swing.JCheckBox();
        facturasCH = new javax.swing.JCheckBox();
        CtasCH = new javax.swing.JCheckBox();
        ReporteVentasCH = new javax.swing.JCheckBox();
        ReporteCtasCH = new javax.swing.JCheckBox();
        ReporteMsVendidoCH = new javax.swing.JCheckBox();
        UsuariosCH = new javax.swing.JCheckBox();
        ConfigCH = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos de usuario");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Datos generales");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nombres: ");

        nombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Apellidos:");

        apellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Dirección: ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Correo electrónico:");

        correo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        direccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Datos de acceso");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Usuario:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Rol:");

        jButton1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Contraseña: ");

        usuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        rol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Cajero" }));

        jButton2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Cédula:");

        identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Sexo:");

        buttonGroup1.add(masculino);
        masculino.setSelected(true);
        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(femenino);
        femenino.setText("Femenino");
        femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeninoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Estado:");

        estado.setText("Activo?");

        cambiarClave.setText("Cambiar clave");
        cambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClaveActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Permisos");

        familiaCh.setText("Familia");
        familiaCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familiaChActionPerformed(evt);
            }
        });

        prodCH.setText("Productos");
        prodCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodCHActionPerformed(evt);
            }
        });

        clientesCH.setText("Clientes");
        clientesCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesCHActionPerformed(evt);
            }
        });

        facturasCH.setText("Facturas de venta");
        facturasCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasCHActionPerformed(evt);
            }
        });

        CtasCH.setText("Cuentas por cobrar");
        CtasCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtasCHActionPerformed(evt);
            }
        });

        ReporteVentasCH.setText("Reportes de ventas");
        ReporteVentasCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteVentasCHActionPerformed(evt);
            }
        });

        ReporteCtasCH.setText("Reportes de cuentas por cobrar");
        ReporteCtasCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteCtasCHActionPerformed(evt);
            }
        });

        ReporteMsVendidoCH.setText("Reporte de productos más vendidos");
        ReporteMsVendidoCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteMsVendidoCHActionPerformed(evt);
            }
        });

        UsuariosCH.setText("Usuarios");
        UsuariosCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosCHActionPerformed(evt);
            }
        });

        ConfigCH.setText("Configuraciones");
        ConfigCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(identificacion)
                                    .addComponent(direccion))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femenino, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(apellidos))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cambiarClave)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(488, 488, 488)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(familiaCh)
                                    .addComponent(prodCH)
                                    .addComponent(clientesCH))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(facturasCH)
                                        .addGap(28, 28, 28)
                                        .addComponent(ReporteVentasCH))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CtasCH)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ReporteMsVendidoCH)
                                            .addComponent(ReporteCtasCH))))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsuariosCH)
                                    .addComponent(ConfigCH))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masculino)
                    .addComponent(jLabel10)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femenino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(estado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cambiarClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(familiaCh)
                    .addComponent(facturasCH)
                    .addComponent(ReporteVentasCH)
                    .addComponent(UsuariosCH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodCH)
                    .addComponent(CtasCH)
                    .addComponent(ReporteCtasCH)
                    .addComponent(ConfigCH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientesCH)
                    .addComponent(ReporteMsVendidoCH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createMap() {
        llaves.put("familia", familia);
        llaves.put("producto", producto);
        llaves.put("clientes", clientes);
        llaves.put("factura", factura);
        llaves.put("ctas", ctaCobrar);
        llaves.put("reporteVentas", repVenta);
        llaves.put("reporteCta", repCta);
        llaves.put("reporteMas", repMas);
        llaves.put("usuarios", usuarioopt);
        llaves.put("configuracion", config);
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (noValido()) {
            return;
        }
        checkCheckboxes();
        createMap();
        String permisos = llaves.toString().replaceAll("\\{", "");
        permisos = permisos.replaceAll("\\}", "");
        permisos = permisos.replaceAll(" ", "");

        this.user.getPersonId().setNames(nombres.getText());
        System.out.println("TF=>" + nombres.getText());
        System.out.println("OB=>" + this.user.getPersonId().getNames());
        this.user.getPersonId().setLastname(apellidos.getText());
        this.user.getPersonId().setPassport(identificacion.getText());
        this.user.getPersonId().setAddress(direccion.getText());
        this.user.getPersonId().setEmail(correo.getText());
        this.user.getPersonId().setSex(sexo);
        this.user.setNick(usuario.getText());
        this.user.setRol(rol.getSelectedItem().toString());
        this.user.setActive(estado.isSelected());
        this.user.setPermissions(permisos.trim());

        if (this.user.getId() == null) {
            try {
                String encriptado = Utilitario.encriptarClave(clave.getText());
                this.user.setPassword(encriptado);
                usuarios.crear(this.user);
                this.dispose();
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(UsuarioForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "No se puede grabar el registro", "ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(UsuarioForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "No se puede grabar el registro", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            usuarios.actualizar(this.user);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean noValido() {
        boolean error = false;
        StringBuilder mensaje = new StringBuilder();
        String cedula = identificacion.getText();
          if (Utilitario.campoVacio(cedula)) {
            error = true;
            mensaje.append("- Campo Cedula obligatorio \n");
        }
          
        if (!Utilitario.validarCedula(cedula)) {
            error = true;
            mensaje.append("- Cédula/RUC incorrecta \n");

        }

        if (Utilitario.campoVacio(usuario.getText())) {
            error = true;
            mensaje.append("- Campo Usuario obligatorio \n");
        }

        if (this.user.getId() == null) {
            if (Utilitario.campoVacio(clave.getText())) {
                error = true;
                mensaje.append("- Campo Clave obligatorio \n");
            }
        }

        if (Utilitario.campoVacio(nombres.getText())) {
            error = true;
            mensaje.append("- Campo Nombres obligatorio \n");
        }
        
                Query q = null;
        //revisar que la cedula no este repetida
        if(this.user.getId()==null){
            q = controller.getEm().createQuery("SELECT u FROM Users u  WHERE u.personId.passport=:cedula");
            q.setParameter("cedula", cedula); 
        }else{
            q = controller.getEm().createQuery("SELECT u FROM Users u  WHERE u.personId.passport=:cedula and  "
                    + "u.personId.id != :idPerson");
            q.setParameter("cedula", cedula); 
            q.setParameter("idPerson", this.user.getPersonId().getId());
        }
        
        List<ClientProvider> clients = q.getResultList();
        if(!clients.isEmpty()){
               error = true;
            mensaje.append("- La cédula ya se encuentra registrada, revise los clientes o usuarios \n");
        }
        

        if (!mensaje.toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, mensaje.toString(),
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        return error;
    }

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
        sexo = "M";
    }//GEN-LAST:event_masculinoActionPerformed

    private void femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeninoActionPerformed
        sexo = "F";
    }//GEN-LAST:event_femeninoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarClaveActionPerformed
        final Users usuario = this.user;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cambiarClave dialog = new cambiarClave(new javax.swing.JFrame(), true, usuario);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_cambiarClaveActionPerformed

    private void checkCheckboxes() {
        familia = (familiaCh.isSelected()) ? 1 : 0;
        clientes = (clientesCH.isSelected()) ? 1 : 0;
        factura = (facturasCH.isSelected()) ? 1 : 0;
        ctaCobrar = (CtasCH.isSelected()) ? 1 : 0;
        repVenta = (ReporteVentasCH.isSelected()) ? 1 : 0;
        repCta = (ReporteCtasCH.isSelected()) ? 1 : 0;
        repMas = (ReporteMsVendidoCH.isSelected()) ? 1 : 0;
        usuarioopt = (UsuariosCH.isSelected()) ? 1 : 0;
        config = (ConfigCH.isSelected()) ? 1 : 0;
        producto = (prodCH.isSelected()) ? 1 : 0;
    }


    private void clientesCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesCHActionPerformed
        clientes = (clientesCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_clientesCHActionPerformed

    private void facturasCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasCHActionPerformed
        factura = (facturasCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_facturasCHActionPerformed

    private void CtasCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtasCHActionPerformed
        ctaCobrar = (CtasCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_CtasCHActionPerformed

    private void ReporteVentasCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteVentasCHActionPerformed
        repVenta = (ReporteVentasCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_ReporteVentasCHActionPerformed

    private void ReporteCtasCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteCtasCHActionPerformed
        repCta = (ReporteCtasCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_ReporteCtasCHActionPerformed

    private void ReporteMsVendidoCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteMsVendidoCHActionPerformed
        repMas = (ReporteMsVendidoCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_ReporteMsVendidoCHActionPerformed

    private void UsuariosCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosCHActionPerformed
        usuarioopt = (UsuariosCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_UsuariosCHActionPerformed

    private void ConfigCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigCHActionPerformed
        config = (ConfigCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_ConfigCHActionPerformed

    private void familiaChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familiaChActionPerformed
        familia = (familiaCh.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_familiaChActionPerformed

    private void prodCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodCHActionPerformed
        producto = (prodCH.isSelected()) ? 1 : 0;
    }//GEN-LAST:event_prodCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UsuarioForm dialog = new UsuarioForm(new javax.swing.JFrame(), true, new Users());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    private Users user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ConfigCH;
    private javax.swing.JCheckBox CtasCH;
    private javax.swing.JCheckBox ReporteCtasCH;
    private javax.swing.JCheckBox ReporteMsVendidoCH;
    private javax.swing.JCheckBox ReporteVentasCH;
    private javax.swing.JCheckBox UsuariosCH;
    private javax.swing.JTextField apellidos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cambiarClave;
    private javax.swing.JPasswordField clave;
    private javax.swing.JCheckBox clientesCH;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JCheckBox estado;
    private javax.swing.JCheckBox facturasCH;
    private javax.swing.JCheckBox familiaCh;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JTextField identificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nombres;
    private javax.swing.JCheckBox prodCH;
    private javax.swing.JComboBox rol;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
